### ISSUE TITLE
Move the `src` directory to `sumatra`

### ISSUE THREAD

**Issue by wd15** [fipymigrate/sumatra#165]
Move the `src` directory to `sumatra` to adhere to Python canonical naming patterns. This relates to installation issues with `python setup.py develop` and `pip install -e hg+https://bitbucket.org/apdavison/sumatra#egg=Sumatra`. See 

     https://groups.google.com/d/msg/sumatra-users/n7AIqk0VvqE/KEoC_Ft8N5sJ

and

     https://groups.google.com/d/msg/sumatra-users/xnCAtoI3P-8/50yPisSDUAYJ
        

 _Imported from Bitbucket issue [179](https://bitbucket.org/apdavison/sumatra/issue/179),  created by wd15 on 05-16-2013 at 13:42, last modified: 05-21-2013 at 09:21_

**Comment by apdavison** [comment]
Implemented in r732, r733, r734 (I was tired, that's why it took three commits instead of one!)
        

_Trac comment by apdavison on 05-21-2013 at 09:21_
