### ISSUE TITLE
Add Postgres support

### ISSUE THREAD

**Issue by wd15** [fipymigrate/sumatra#167]
Pull-request for Postgres support:

    https://bitbucket.org/apdavison/sumatra/pull-request/14/add-support-for-postgres/diff

        

 _Imported from Bitbucket issue [181](https://bitbucket.org/apdavison/sumatra/issue/181),  created by wd15 on 05-26-2013 at 00:53, last modified: 06-01-2013 at 00:15_

**Comment by apdavison** [comment]
Merged in r742
        

_Trac comment by apdavison on 06-01-2013 at 00:15_
